# Generated by Django 5.0.1 on 2024-03-27 06:54

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organos',
            fields=[
                ('ID', apis.models.UnsignedIntAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('aparato_sistema', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('detalle_organo_ID', models.PositiveIntegerField()),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_transplantes',
            fields=[
                ('ID', apis.models.UnsignedIntAutoField(primary_key=True, serialize=False)),
                ('paciente_ID', models.IntegerField()),
                ('medico_ID', models.IntegerField()),
                ('organo_ID', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Moderada', 'Moderada')], max_length=255)),
                ('fecha_solicitud', models.DateTimeField()),
                ('dias_espera', models.IntegerField()),
                ('estatus', models.CharField(choices=[('Transplante exitoso', 'Transplante Exitoso'), ('Recuperacion', 'Recuperacion'), ('Pendiente', 'Pendiente')], max_length=255)),
                ('estatus_aprobacion', models.BooleanField(default=False)),
            ],
        ),
    ]
