# Generated by Django 5.0.2 on 2024-04-17 17:05

import apis.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('ID', apis.models.UnsignedIntAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45, null=True)),
                ('nombre', models.CharField(max_length=80)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(max_length=80, null=True)),
                ('curp', models.CharField(max_length=18, null=True, unique=True)),
                ('genero', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N/B', 'Nb')], max_length=50)),
                ('grupo_sanguineo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'Ab'), ('O', 'O')], max_length=50)),
                ('tipo_sanguineo', models.CharField(choices=[('+', 'Positivo'), ('-', 'Negativo')], max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='dias_espera',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='estatus',
            field=models.CharField(choices=[('Transplante exitoso', 'Transplante Exitoso'), ('Recuperacion', 'Recuperacion'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='estatus_aprobacion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='organo_ID',
            field=apis.models.UnsignedForeignKey(db_column='organo_ID', on_delete=django.db.models.deletion.CASCADE, related_name='fk_organo_ID', to='apis.organos'),
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='prioridad',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Moderada', 'Moderada')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='organos',
            table='organos',
        ),
        migrations.AlterModelTable(
            name='solicitud_transplantes',
            table='solicitud_transplantes',
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('persona_ID', apis.models.UnsignedForeignKey(db_column='persona_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.personas')),
                ('nss', models.CharField(max_length=15, null=True)),
                ('tipo_seguro', models.CharField(max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_cita', models.DateTimeField()),
                ('estatus_medico', models.CharField(default='Normal', max_length=100, null=True)),
                ('estatus_vida', models.CharField(choices=[('Vivo', 'Vivo'), ('Finado', 'Finado'), ('Coma', 'Coma'), ('Vegetativo', 'Vegetativo')], default='Vivo', max_length=50)),
                ('estatus', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='personal_medico',
            fields=[
                ('persona_ID', apis.models.UnsignedForeignKey(db_column='persona_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.personas')),
                ('especialidad', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Médico', 'Medico'), ('Enfermero', 'Enfermero'), ('Administrativo', 'Administrativo'), ('Directivo', 'Directivo'), ('Apoyo', 'Apoyo'), ('Residente', 'Residente'), ('Interno', 'Interno')], max_length=50)),
                ('cedula_profesional', models.CharField(max_length=50, null=True, unique=True)),
                ('departamento_ID', models.PositiveIntegerField()),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Jubilado', 'Jubilado'), ('Permiso', 'Permiso')], max_length=50)),
                ('fecha_contratacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_termino_contrato', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'personal_medico',
            },
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='paciente_ID',
            field=apis.models.UnsignedForeignKey(db_column='paciente_ID', on_delete=django.db.models.deletion.CASCADE, related_name='fk_paciente_ID', to='apis.pacientes'),
        ),
        migrations.AlterField(
            model_name='solicitud_transplantes',
            name='medico_ID',
            field=apis.models.UnsignedForeignKey(db_column='medico_ID', on_delete=django.db.models.deletion.CASCADE, related_name='fk_medico_ID', to='apis.personal_medico'),
        ),
    ]
