# Generated by Django 5.0.1 on 2024-04-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('DROP FUNCTION IF EXISTS fn_calcular_dias_espera;'),
        migrations.RunSQL(
            '''
                CREATE FUNCTION `fn_calcular_dias_espera`(fecha_solicitud datetime) RETURNS int
                DETERMINISTIC
                BEGIN
                    SET @dias_espera = DATEDIFF(fecha_solicitud , NOW());
                    RETURN @dias_espera;
                END
            '''
        )
    ]
