# Generated by Django 5.0.1 on 2024-04-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', 'triggers_transplantes'),
    ]

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS vista_prioridad_transplantes;'),
        migrations.RunSQL(
            '''
                CREATE VIEW `hospital`.`vista_prioridad_transplantes` AS
                    SELECT 
                        `hospital`.`solicitud_transplantes`.`prioridad` AS `prioridad`,
                        COUNT(0) AS `cantidad_solicitudes`
                    FROM
                        `hospital`.`solicitud_transplantes`
                    GROUP BY `hospital`.`solicitud_transplantes`.`prioridad`
            '''
        ),   
    ]